spring:
  application:
    name: product-service

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
  instances:
    reviewsCB:
      baseConfig: default
